server:
  port: 8081

spring:
  application:
    name: ingestion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/webhook_db
    username: webhook_user
    password: webhook_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379